### ISSUE TITLE
Mittag und Abendsmensa

### ISSUE THREAD

**Issue by FlorianXXIV** [FlareFlo/menser#2]
currently menser portrays all entires of the day for mensa1

including duplicate entries for noon and evening dishes. Since they aren't always the same, it would be useful to have an indication if a given dish is served during evening or noon times.

the API provides the "time" tag for every dish, which is (currently) either "noon" or "evening",you can maybe use that

![ferris](https://github.com/FlareFlo/menser/assets/57264002/34a38596-4f87-4af5-a6b6-3c08f427ae74)

**Comment by FlorianXXIV** [comment]
also, the reason for the ID change is that now the location itself has it's opening hours listed. meaning that you don't need to rely on picking a meal from the menu to get those.

**Comment by FlareFlo** [comment]
I will group meals by their opening hours and re-render the table with said differences
